package coderhood.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

@Getter
@Setter
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TB_AREA", schema = "ADMIN") // important: schema = ADMIN
public class Area {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // because Oracle DDL uses "GENERATED BY DEFAULT AS IDENTITY"
    private Long id; // because your DDL says NUMBER(19), map as Long

    @Column(length = 255)
    private String cidade;

    @Column(length = 255)
    private String estado;

    @Column(nullable = false, length = 255)
    private String nome;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 255)
    private StatusArea status = StatusArea.EM_ANALISE;

    @OneToMany(mappedBy = "area", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<Talhao> talhoes = new ArrayList<>();

    public void addTalhao(Talhao talhao) {
        talhoes.add(talhao);
        talhao.setArea(this);
    }

    public void clearTalhoes() {
        talhoes.forEach(talhao -> talhao.setArea(null));
        talhoes.clear();
    }
}
