CREATE TABLE tb_area (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL,
    estado      VARCHAR(255),
    cidade      VARCHAR(255),
    status      VARCHAR(50) NOT NULL
);